### ISSUE TITLE
Update generated download file to correctly label the columns in the federal revenue by company file. 

### ISSUE THREAD

**Issue by lpgoldstein** [DOI-ONRR/nrrd#1826]
**Current column header -> new header**
Corporate Name -> Company Name
Revenue Agency Type -> Revenue Type

**Comment by Maroyafaied** [comment]
@mojobnichols let's go ahead and get the download file to match the database. I didn't find any past conversations with DORC why we shouldn't. Also , I noticed in the query tool there's two N/A and also also we need to change "oil & gas" to "oil & gas (pre-production). 
![image](https://user-images.githubusercontent.com/40175688/143945118-3fe68c45-6a9f-471e-986d-e37cf524ddc6.png)
![image](https://user-images.githubusercontent.com/40175688/143945150-e81b7efe-ea4e-467b-ad8a-852b01faa029.png)

**Comment by Maroyafaied** [comment]
@mojobnichols @lpgoldstein  We should be receiving CY 2021 revenue by company data in the coming weeks so I will move this issue out of this sprint and approach it once we're updating the data set.

**Comment by greensomes** [comment]
There are multiple "Geothermal" commodities as well. As with the "N/a" values, it's due to a blank space at the end.

The refactored process includes fixes to trim blank spaces from the commodity values. A script will need to be run to update the existing values.

**Comment by greensomes** [comment]
I added an anonymous changeset to update the existing commodity values. "Geothermal" and "N/a" have been fixed and "Gas & oil" is updated to "Gas & oil (pre-production)".

**Comment by greensomes** [comment]
@Maroyafaied, the commodity dropdown [here](https://nrrd-preview.app.cloud.gov/sites/2887-revenue-by-company/query-data) reflects the changes mentioned above. Please have a look when you have a moment. Thanks!!

**Comment by Maroyafaied** [comment]
@greensomes I see the changes in the query tool dropdown. The generated download still has the columns labeled as "Corporate Name" and "Revenue Agency Type", those should be changed to "Company Name' and "Revenue Type". @lpgoldstein once the columns in the file have changed, can you also change the download page to say "Company Name" (2nd screenshot)
 [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3FRQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ee2637ee52bff2e80fcb420f32f0dfcc9e411527/image.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzJRQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--15dcc854e10fb05f1fede1fca24cdd0a368ab13b/image.png)

Also, this is not mentioned in this issue but there's another issue #2702 for it, the query tool lists "AML Fees including Audits and Late Charges" twice under revenue type, can that be fixed with the refactoring? If so, I'll add that issue to this sprint.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2FRQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d31f00889b2f4cc4f5792e6ae3160bfc7a01bdb0/image.png)
