### ISSUE TITLE
Explore Data - Revenue - Alaska County Card bug

### ISSUE THREAD

**Issue by cthomasONRR** [DOI-ONRR/nrrd#2270]
In Explore Data - Revenue - both calendar year and fiscal year - the Alaska county cards are appearing as below:
![image.png](https://images.zenhubusercontent.com/60f9807ebc2bf779cc3921f2/f736c7af-1e93-4e91-aa7b-ce78748efc23)

It looks like this Umiat County card has the combined data for the following counties: Harrison Bay, Ikpikpuk Riv, Kenai (Post), Naknek, Teshekpuk, Umiat. The only other county displayed as having data on the map is Kenai (Pre)... and their O&G (pre-prod) data is incorrect.

![image.png](https://images.zenhubusercontent.com/60f9807ebc2bf779cc3921f2/103aaf2d-d1a8-461f-8a18-0d9b67044649)

This bug seems to be for all fiscal and calendar years.

We need to:

- [ ] Either make sure every county with data has its own card, or clearly state what counties are included in the existing combined card that just says "Umiat County"
- [ ] Make the Oil & Gas (pre-production) commodity from appearing multiple times on 1 card
- [ ] Make the Oil & Gas (pre-production) commodity  on the Kenai (Pre) card the correct number

**Comment by Maroyafaied** [comment]
@greensomes moving this to next sprint since redirects are taking priority

**Comment by Maroyafaied** [comment]
@Baymatt have you had a change to audit this bug yet?

**Comment by Baymatt** [comment]
@Maroyafaied I have, I'm not 100% done with all the counties but I have found a few items of note which I will compile in a list and post on this issue hopefully by the end of the weekend.

**Comment by Baymatt** [comment]
Running List 
- [ ] Mobile County in Alabama has a similar issue to the counties in Alaska
- [ ] Santa Barbara County in California is spelled incorrectly as Santa Barbar in the County Card and in our dataset

<img width="305" alt="Screenshot 2023-01-02 at 12 11 01 AM" src="https://user-images.githubusercontent.com/43329595/210207177-74fb8538-e38f-4d69-a37f-7911a2c3fbf5.png">

**Comment by Baymatt** [comment]
@Maroyafaied @cthomasONRR I took a look just now at some summary cards for states like you mentioned. I found that summaries were being displayed instead of the text for certain states without data. Also, the text seems to still indicate a range of years even with only one year selected. "...did not have revenue from to 2021"

<img width="571" alt="Screenshot 2023-01-04 at 11 20 06 AM" src="https://user-images.githubusercontent.com/43329595/210632869-38360195-0d14-4dd1-8498-a3efe3647765.png">

<img width="570" alt="Screenshot 2023-01-04 at 11 17 22 AM" src="https://user-images.githubusercontent.com/43329595/210633168-e7ba8d59-c1db-4d51-b578-65006c4653a3.png">
