### ISSUE TITLE
NRRD Release Training

### ISSUE THREAD

**Issue by AlexandracmONRR** [DOI-ONRR/nrrd#2382]
- Discuss NRRD release
- Discuss about duties when acting for Maroya

**Comment by Maroyafaied** [comment]
I usually create a new pull request to update the "what's new" section and the version but I will be updating those in the open pull request for data since that branch has the changes to the configuration file that allowed circle ci to build successfully. If I'd open a new branch, then I'd have to change the config file to match so it's easier to keep everything in one pull request for this release. 
![image.png](https://images.zenhubusercontent.com/5c58acad07cc4d6f39e54f67/b0bf8676-e703-48af-affe-e312dbf8861e)
![image.png](https://images.zenhubusercontent.com/5c58acad07cc4d6f39e54f67/a6a06755-6469-4ec7-b714-74109db5149b)
