### ISSUE TITLE
NRRD Homepage - update production yearly source file url

### ISSUE THREAD

**Issue by cthomasONRR** [DOI-ONRR/nrrd#2402]
Yearly source file is pointing to monthly, need to update it to point to yearly.

https://revenuedata.doi.gov/downloads/production/ instead of  https://revenuedata.doi.gov/downloads/production-by-month/

![image.png](https://images.zenhubusercontent.com/60f9807ebc2bf779cc3921f2/e4c822c7-e69c-41d0-bcc4-47ee9acb457a)

**Comment by Maroyafaied** [comment]
@cthomasONRR production homepage charts are created using the monthly data files. This is why we have a bar for FY 22 even though we don't have the fiscal year production file from DORC yet. We decided to use the monthly files since we are only showing oil, gas, and coal and not all the commodities that are in yearly files.

**Comment by cthomasONRR** [comment]
@Maroyafaied OOPS! Sorry I'm reviewing the site map and got confused. I'll make a note in the site map that the yearly production should be pointing to the monthly source file.
