### ISSUE TITLE
Add user interview & consent process flowchart and info to wiki

### ISSUE THREAD

**Issue by eelzi-ONRR** [DOI-ONRR/nrrd#2514]
This was a great suggestion that came out of the hallway interviews for the user research agreement

**Comment by lpgoldstein** [comment]
@AlexandracmONRR Do you have time to review this? Thanks! https://github.com/DOI-ONRR/nrrd/wiki/User-Research-Agreement-Process

**Comment by AlexandracmONRR** [comment]
@lpgoldstein Absolutely - I will do that now!

**Comment by AlexandracmONRR** [comment]
@lpgoldstein - Please see my corrections below (I've tried to make them as organized as possible and I marked them with **bold text**, but let me know if you have any questions):

_Intro Text:_
**The Open Data, Design, and Development (ODDD) team wrote this wiki to be used by research participants. It will guide research participants through the UX research process.**

_Workflow Illustration:_
General:
I think you could have a long skinny box over boxes 2 and 3 that says "During the interview".
Box 1: 
Title change to "Before interview"
Make an accommodation request **(if needed)**
Box 2: 
Title change to "Start of interview"
Ask questions **(if any)**
Opt-in to participate **(optional)**
Box 3: 
Title change to "End of interview"
Opt-in to **allow** your feedback to be used **anonymously** in **research analysis (optional)**


_Before the interview:_
Title change to "Before interview"
2. If you **opt-in** to participate, you’ll receive an outlook invitation with your scheduled time and additional details of the study. The invitation will include a link to the User Participation Agreement.
4. The ODDD **team** contact will follow-up the day before the interview to confirm your participation.
5. The interview will be conducted via Microsoft Teams by **a member of the ODDD team**. One person will be conducting the interview, and one or more **team members** will be taking notes. If you require an accommodation, let your ODDD team contact know at least 2 days prior to the interview.


_At the start of the interview:_
Title change to "Start of interview"
Fix numbering of first line to "6"
6. You will be reminded of the User Research Agreement, and allowed time for **questions** about the agreement or research process.
Add another line: **7. You will have the opportunity to opt-in or opt-out of research participation.** [I thought we may want this to match the workflow boxes so I added this line... you may want to reword this because I'm not sure if this is a formal step or if participants should just be aware that they can opt-in or opt-out at any time.]

_At the end of the interview:_
Title change to "End of interview"
Fix numbering of next lines to "8" and "9"
8. You will have another opportunity to **opt-out** of having your feedback included in our data. If you opt-in your feedback will be deidentified **(or anonymized)** and included in the research results.
9. After all interviews are conducted, the ODDD team will collate the findings and make recommendations for improvements. The research summary and analysis will be publicly shared on our wiki.

**Comment by lpgoldstein** [comment]
@eelzi-ONRR Please review one more time and then this is good to close: https://github.com/DOI-ONRR/nrrd/wiki/User-Research-Agreement-Process

Can also discuss on Friday if needed.

**Comment by eelzi-ONRR** [comment]
@lpgoldstein I fixed some typos, added links, reworded #1 to not use "received" twice, and moved the acccomodation sentence further up to it's own number and in a chronological order that makes sense for 2-days prior to the interview.

I'm out on Friday, but feel free to make any additional changes and then close this out.

**Comment by eelzi-ONRR** [comment]
I changed the page name so it changed the URL: https://github.com/DOI-ONRR/nrrd/wiki/User-research-process
