### ISSUE TITLE
Develop a sitemap.xml 

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/nrrd#2641]
This was identified as missing [required link](https://digital.gov/resources/required-web-content-and-links/?=checklist) according to the [Site Scanning program](https://digital.gov/guides/site-scanning/) - an effort to maintain a catalog of all public federal .gov websites and to scan them daily for a bunch of (hopefully useful) data.

**Comment by Maroyafaied** [comment]
test

**Comment by lpgoldstein** [comment]
@eelzi-ONRR Here are the directions for the sitemap: 

I added a robots.txt file in https://github.com/DOI-ONRR/nrrd/pull/3157. As of now the file disallows the archived site from being indexed. The robots.txt file should also include the sitemap url but that line will need to be added later since we haven't developed the sitemap yet for nrrd. Once you have a sitemap xml file and you've added it to the public folder, you'll simply add this line to the robots.txt file "Sitemap: https://revenuedata.doi.gov/sitemap.xml"

Here's the location of the robots.txt file nrrd\database\public\robots.txt

**Comment by eelzi-ONRR** [comment]
SItemap has been added to PR #3157
