### ISSUE TITLE
Review Sitemap to 6.0

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/nrrd#2928]
Once @AlexandracmONRR is done with making updates

**Comment by cthomasONRR** [comment]
- **File Collection**: File collection can be used for CMS collections, file download lists, or video lists or cards/titles with documents listed (since we are not mapping out each individual document). Cards with file downloads and video collections should include the number of file downloads or videos linked. Use the orange stacked boxes.
- **Contact Categories/Cards**: two types of contact cards - a singular category card for a specific contact (simple yellow box) and a multiple category contact card for several contacts that includes number of contacts (stacked yellow box).
- **External Links**: do NOT use the numbering hierarchy throughout the site map; but include a part of the URL underneath the title of the external link.
- **Internal Links**: do NOT use the numbering hierarchy, but dynamically link to the correct page
- **Introductory text links**: Sections that have links that show up in the introductory text but without a subtitle, should be inserted at the top by adding a "0" to the end.
- **Note pages that are exceptions**: note pages that have exceptions to the format; this is often due to the complexity of the pages. For example: 3.8.5, 3.8.5.1, 3.8.5.2 are all extremely complex pages that have been formatted as more high level.

**Comment by AlexandracmONRR** [comment]
@cthomasONRR - thank you for helping with the review. Please see the axure link here: https://71ccqt.axshare.com

**Comment by cthomasONRR** [comment]
@AlexandracmONRR @Maroyafaied  I'm done reviewing up to 6.0. Please let me know if you have any questions about my comments. Thanks!
