### ISSUE TITLE
Review sales data query tool for data accuracy & design 

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/nrrd#3065]

**Comment by Maroyafaied** [comment]
https://nrrd-preview.app.cloud.gov/sites/federal-sales-data/query-data/

**Comment by Maroyafaied** [comment]
@greensomes I checked the data and played around with filtering and the data looks great and all correct! Great Job!! The only design issue I saw is the "add column" is cut off for me but not sure if it's because my screen size. <img width="462" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDk2QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ee97fa8248f664e688f90879e5930c64a46a2bf4/image.png" alt="image.png" />

**Comment by eelzi-ONRR** [comment]
@greensomes Thanks so much for your work on this!

Things I checked that look good:

- Sales Volume total appears when one commodity is selected and shows NA when multiple are selected
- Add/Remove column button works
- If I select a state with only one commodity the commodity dropdown and table display adjust accordingly
- Filters work as expected, no typos found
- Sort arrows work
- Download files match selected filters

Things I checked with questions or concerns:
- Lowercase MMBtu - just making sure this was asked about? I never heard if it was okay to be all lower case or not
- Remove column button is below the dropdown but on other explore data pages it's above. Was this intentional? 
- When I have the page at 90% or higher, *Sales Volume total not available..." message is real close to the horizontal scroll bar. Can we move it a few pixels lower? <img width="751" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTk2QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--308c59ef3983f8090009090062a305e93caf6e0a/image.png" alt="image.png" />
- On the download tab we should add a Source File and Documentation link to the data download page like there is for the other data types in query
- The Add Column link is shifting the Sales Year label down do it's not in lien with the others. Is it possible to have the Add Column link inline with the upward caret instead so the column labels remain flush?

**Comment by Maroyafaied** [comment]
@greensomes it would be nice to add the following two items from Erin's review before we conduct user research:

- Change mmbtu to upper case MMBtu
- On the download tab we should add a Source File and Documentation link to the data download page like there is for the other data types in query (see screenshot below) <img width="973" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHVKQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--11182ff499049a33c70212f2220a6147506f45f9/image.png" alt="image.png" />

Also, Erin and Alex are not seeing the "add column" being cut off like I am, I only see this when using Chrome but not when using Microsoft Edge so it might be just something with my settings, we can observe how it looks when we're conducting user interviews. <img width="462" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDJKQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1ddda0a97ecd87fe83adf73531c537deb81515fb/image.png" alt="image.png" />
