### ISSUE TITLE
Recruit for Sales Data user research

### ISSUE THREAD

**Issue by AlexandracmONRR** [DOI-ONRR/nrrd#3105]
Draft recruiting email & start recruiting

**Comment by AlexandracmONRR** [comment]
January 3-12: Participant recruitment

**Comment by eelzi-ONRR** [comment]
I removed the training tab from the recruitment sheet since that was specific to the users for the previous study. And I rewrote the email further down in that doc so we have both versions to look at. I changed the email to be very clear what we're looking at (the addition of sales data, prototypes and WIP instead of live pages), and detailed what kinds of users we're looking for in this study - that way if we contact someone who doesn't actually have a connection to sales data, they can opt out instead of us wasting their time
