### ISSUE TITLE
Explore data: Amounts less than $1,000 show an extra zero at the end on the summary cards

### ISSUE THREAD

**Issue by eelzi-ONRR** [DOI-ONRR/nrrd#3111]
The comparison cards don't show what's after the decimal - can we make the summary cards do the same? This applies to small numbers only - larger numbers already don't show the decimal

https://revenuedata.doi.gov/explore/?dataType=Revenue&location=FL%2CAZ&mapLevel=State&offshoreRegions=false&period=Calendar%20Year&year=2022

<img width="777" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNnVUQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--010048bc05a83bbe9d3a3cce4c3ed7ad1a352686/image.png" alt="image.png" />

**Comment by greensomes** [comment]
@eelzi-ONRR,  I have updated the code to use a standard JavaScript API rather than a deprecated third-party library. Please see the comparisons of these changes below. The first screenshot is the current live site.

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVphQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--67062d45c31c487e5834ab1a54a9b753187d49b4/image.png" alt="image.png" />

And the proposed changes:

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBenBjQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--af800a17c111b88812a788c42affdd8f5c6ac0a2/image.png" alt="image.png" />

The [dev site](https://dev-nrrd.app.cloud.gov/explore?dataType=Revenue&location=NF%2CNA%2CFL%2CKS&mapLevel=State&offshoreRegions=false&period=Calendar%20Year&year=2022) contains the fix as well. Thanks!

**Comment by eelzi-ONRR** [comment]
@greensomes  I checked the states you have shown and the ones from my screenshot - they all look good!
