### ISSUE TITLE
Add glossary hover over for Unit Value on DD page for federal sales

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/nrrd#3220]
For unit value in process diagram and for TA & PA in query tool.
<img width="698" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0UxQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d96fbf6e9025e0de0aa37b526f6b2c5789d346d6/image.png" alt="image.png" />
<img width="1527" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0kxQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b18c92f64b24a509bc027e5c092ef3a63fd3e13c/image.png" alt="image.png" />

**Comment by AlexandracmONRR** [comment]
I believe that we should simply add "Unit Value" to the Data Dictionary section for the Federal Sales DD page. Unit Value is already a defined term, so this would be fairly simple addition.

This differs in the original recommendation, because we wanted to add it to the equation in step 1 of the process diagram. However, because we changed this equation to an image with alt text, we can no longer do a hover over definition here. Unit Value is not used within the description of this step, so we cannot simply move the hover over earlier in the text. That's why I made my recommendation above.

@lpgoldstein and @eelzi-ONRR - do you agree with this action?

**Comment by eelzi-ONRR** [comment]
Sure that seems like a good, simple solution. 

Would we consider a note after the equation along the lines of "Definitions for the equation parts are included in the Data Dictionary section on this page". Or is that overkill?

**Comment by AlexandracmONRR** [comment]
@eelzi-ONRR - i think it may be overkill but I could be convinced otherwise if Lindsay thinks users will benefit from it!

**Comment by AlexandracmONRR** [comment]
Unit Value definition was added to Data Dictionary as a part of PR 3372.
