### ISSUE TITLE
Get ZenHub paid plan approval

### ISSUE THREAD

**Issue by cthomasONRR** [DOI-ONRR/nrrd#3227]

**Comment by Maroyafaied** [comment]
Sent this email to Joe and Nathan.

My team uses ZenHub as our project management tool since it integrates with GitHub.  We heavily rely on this tool for our work planning. ZenHub granted us free usage for a year since we use open-source code. The free usage plan will expire in about two months and ZenHub changed it's policy to only grant free usage to only projects offering humanitarian aid. 

We will have to pay for licenses to be able to continue this tool, the cost is about $8/month/user, there are 6 members on the ODDD team so the total annual cost will be about $577. 

I would like to get  licenses approved and purchased for my team before I leave ONRR to avoid the team facing work interruptions in a couple of months. Or I would at least like to get the process started for them if possible. 

Below is the link to the plan costs. Please let me know if I can provide any other information. Thanks for your help!

https://www.zenhub.com/pricing

**Comment by cthomasONRR** [comment]
@Maroyafaied Thanks for getting this started, we appreciate you!

**Comment by Maroyafaied** [comment]
@cthomasONRR you're welcome. Unfortunately, Zen Hub's management team didn't allow for us to have a 30 day extension.

**Comment by cthomasONRR** [comment]
Nathan is still looking into ZenHub as a short-term option, maybe paying for ~3 months. Money isn't the holdup, but the concern is that it's not FedRAMP authorized and doesn't have an ATO. 

He and Joe seem ok with paying for it short-term, but long term might me a transition to Jira. Jeff is researching to see if Jira has all the GitHub integrations/capabilities as ZenHub.

**Comment by lpgoldstein** [comment]
In process and waiting to hear back from ZenHub sales

**Comment by lpgoldstein** [comment]
Moving because both Joe and Nathan are on leave through the end of the week. Will address next sprint
