### ISSUE TITLE
Review sales data download for plain language 

### ISSUE THREAD

**Issue by lpgoldstein** [DOI-ONRR/nrrd#3272]
CHECKLIST FOR DOWNLOAD DATA:
- [x] Scope - Alex
- [x] Sales vs accounting year - Alex
- [x] COVID royalty relief - Christine
- [x] Data dictionary - Christine
- [x] Alt text for images - Lindsay - no images need alt text. royalty equations are tables. 

CHECKLIST FOR GLOSSARY:
- [x] Land category - Lindsay (keeping as-is)
- [x] Land class - Lindsay (keeping as-is)
- [x] Not tied to a commodity
- [x] RVLA (keeping as-is)
- [x] Sales year

**Comment by cthomasONRR** [comment]
Here are the sections of the download data page that needs reading level reductions. The NRRD content audit is updated.

![image](https://github.com/DOI-ONRR/nrrd/assets/72526208/695af8d8-f5d8-4c2d-90b2-3666a4971220)

**Comment by AlexandracmONRR** [comment]
@cthomasONRR - Proposed scope rewrite that was rated grade level 10 in Hemingway Editor (thanks to Lindsay and Erin for their review and edits):

**Scope**

ONRR collects the data from the Sales and Royalty Remittance Report, Form ONRR-2014. Reporters submit Form ONRR-2014 to provide information on royalties due based on sales or use of the natural resource production.

ONRR collects revenues on over 60 different products, but this dataset only includes data for U.S. federal onshore lands and offshore areas for oil, gas, and NGLs. It does not include Native American land, privately-owned lands, or U.S. state lands. The dataset includes all ONRR Form-2014 federal reported royalty transaction codes, royalty relief codes, and transaction code (TC) 13 Quality Bank and Gravity Bank Adjustments.

After reporters submit Form ONRR-2014, ONRR aggregates the data by totaling the data values by the sales year. ONRR then publishes this dataset.

**Comment by cthomasONRR** [comment]
@AlexandracmONRR I'm getting grade 11 in Hemingway. Hemingway is a bit weird in that you have to make sure there are no empty line spaces before the start of your text. If you don't remove those it sometimes gives false readability scores. I'll work on lowering this to grade 10 when I have time. 
![image](https://github.com/DOI-ONRR/nrrd/assets/72526208/b31265d6-17a1-4fdc-afa8-03e4a4d1fcf8)

**Comment by cthomasONRR** [comment]
@AlexandracmONRR If you break out what this dataset contains in bulleted format, it drops to grade 9. Maybe we should break this out in bullets because it highlghts what's included in the dataset and I remember some research participants had trouble identifying that only federal oil, gas, and NGLs were included. 

![image](https://github.com/DOI-ONRR/nrrd/assets/72526208/21be0c05-20f0-44ed-a855-06c78acd91d2)

**Comment by AlexandracmONRR** [comment]
The scope has been updated in the "federal-sales-data-productcodes" PR.

**Comment by lpgoldstein** [comment]
@cthomasONRR I think land class is testing at higher grade level because of sentence format. 

Land class - glossary - Distinguishes federal lands and waters from Native American lands within the ONRR datasets. G10
download page -This field distinguishes federal lands and waters from Native American lands. All data in this dataset is federal. G7

Land category tests at a grade 10 in the glossary so I think that's okay too. 

The download page definition comes in at 11 but if we remove a few words -  situated or occurring - it goes down to a 10

Land Category:

Onshore (Federal): Lands that are owned by or under the jurisdiction of the federal government and are **on** land. Onshore land includes public domain lands, acquired lands and military acquired lands.

Offshore (Federal): Submerged lands that are located farther than three miles off a state's coastline, or three marine leagues into the Gulf of Mexico off Texas and Western Florida and are owned by or under the jurisdiction of the federal government. [Outer Continental Shelf](http://www.boem.gov/OCS-Lands-Act-History/) lands are included.

**Comment by cthomasONRR** [comment]
@lpgoldstein Please review. I'll review your comment above now...

COVID rewrites:

What is COVID royalty relief?

Under 30 CFR 203.80, the Bureau of Safety and Environmental Enforcement (BSEE) can grant special case royalty relief on a product or lease basis. This royalty relief is granted through an application-based process that adheres to strict criteria. In 2020 and 2021, BSEE granted limited royalty relief known as COVID royalty relief. COVID royalty relief is separated in this dataset because payors were not required to report a product.

![image](https://github.com/DOI-ONRR/nrrd/assets/72526208/e012b0f6-08af-4ba7-ac0e-dd07692c5110)

![image](https://github.com/DOI-ONRR/nrrd/assets/72526208/ba3bdfbd-4b63-492e-a9d0-4a214914d880)

**Comment by cthomasONRR** [comment]
Lindsay and I discussed Land Class and Land Category. We are going to keep them as-is.

**Comment by AlexandracmONRR** [comment]
@cthomasONRR and @lpgoldstein - With Lindsay's help I was able to get this pretty accurate and at a grade 10 level. Please review and let me know if there should be changes.

***

Although sales year and accounting year appear similar, there are key differences: 

Sales year data includes sales transactions records for a specific year* without adjustments for previous years. This data provides a snapshot of reported sales. It is useful for analyzing sales trends and comparing them to production volumes. The data changes, so ONRR publishes them with an as-of date. The Federal Sales dataset is sales year data reported on a calendar year basis. 

Accounting year data includes sales transaction records accepted by ONRR within a specific year* with adjustments for previous years. The data shows the money ONRR collected and disbursed from the current year and any adjustments or corrections for previous years. It does not provide accurate trend analyses of sales values or volumes over time.

*federal fiscal year or calendar year

**Comment by lpgoldstein** [comment]
@AlexandracmONRR I like it!

**Comment by cthomasONRR** [comment]
@AlexandracmONRR I'm OK with this. I'd suggest saying "The federal sales dataset is sales year data reported on a calendar year basis." right at the beginning and lower case "federal sales" 

![image](https://github.com/DOI-ONRR/nrrd/assets/72526208/91bcc26d-3290-490c-9e4a-12f38dd5d73b)

**Comment by cthomasONRR** [comment]
@lpgoldstein 

I made the following minor changes to Calendar Year and Sales Volume definitions. With these changes, the data dictionary is now at grade 10. Most of the other definitions are consistent throughout the download data pages, so I don't want to make inconsistent changes.

Updating calendar year will make it consistent with that definition on other pages.
For sales year, removing a note about geothermal makes sense to me because geothermal is not in this dataset.

![image](https://github.com/DOI-ONRR/nrrd/assets/72526208/7d397e3f-a981-4868-91af-050ebc62b42e)

![image](https://github.com/DOI-ONRR/nrrd/assets/72526208/9731f3d1-f7d2-4c06-a790-c3f0f74daadb)

**Comment by lpgoldstein** [comment]
@cthomasONRR Thanks - agree that we should remove geothermal.
