### ISSUE TITLE
Remove PII from past user research files

### ISSUE THREAD

**Issue by eelzi-ONRR** [DOI-ONRR/nrrd#3298]
We need to review all past user research folders for storage of unnecessary PII. 

- [x] Restricted access to RPP to ODDD team
- [x] Restricted access to UX folders to ODDD team

NRRD User Research Folder (Alex):

- [x] Removing names and emails from the spreadsheet, making sure that roles/teams are documented in the sheet if possible 
- [x] Review the participant interview notes sheets to make sure names aren't included - remove names if they are

Onrr.gov User Research Folder (Erin):

- [x] Removing names and emails from the spreadsheet, making sure that roles/teams are documented in the sheet if possible 
- [x] Review the participant interview notes sheets to make sure names aren't included - remove names if they are

**Comment by AlexandracmONRR** [comment]
@eelzi-ONRR and @lpgoldstein please see the considerations below related to removing the PII from past user research. 

- Consent forms: typically includes first and last names - i believe we can keep these since it only includes the participant's name
<img width="624" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzlDQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--82bec4aeaf4f5c21db186cbc06ed2410f2178ae5/image.png" alt="image.png" />



- Participant excel sheet - we should delete the emails from the document. We should make sure that the role title and team is present and accurate so we can have more context to data when using it for the future. Should we delete the name as well?
<img width="1614" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0JEQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4863bc6815ccc72fddc299a2ce6f976b9b2b2e49/image.png" alt="image.png" />
- Interview Notes: delete any names or emails present (very uncommon to include these - this would be a quick sweep of the notes to make sure that the names and emails are not included

**Comment by eelzi-ONRR** [comment]
@AlexandracmONRR yes - all of that will meet our requirements for PII

For future studies, I think we should consider a folder that only the research team members have access to - so it has more restrictions than the rest of the ODDD team folders. Anything that has PII in it should be kept in these folders, since we sometimes give temporary access to our folders to others in ONRR.

Thinking more about it - we should probably put similar restrictions on our Research Participant Pool files so they cannot be available to anyone we give temporary ODDD access to.

**Comment by lpgoldstein** [comment]
@eelzi-ONRR Im in the RPP now so will change the permissions.

**Comment by AlexandracmONRR** [comment]
@eelzi-ONRR - thanks for the input, for now @lpgoldstein has restricted access on the participant pool spreadsheets to just our team.

I agree that for future studies we can create recruitment folders that restrict access to just our team to protect PII.

**Comment by AlexandracmONRR** [comment]
@eelzi-ONRR - I've added the assignments for removing PII to the description at the top as a check list.

**Comment by eelzi-ONRR** [comment]
It looks like we've all checked our tasks as complete - @AlexandracmONRR @lpgoldstein can we close the issue?

**Comment by AlexandracmONRR** [comment]
Yes, I think we are good to close it!
