### ISSUE TITLE
Test Intern research tips and tricks document and process

### ISSUE THREAD

**Issue by lpgoldstein** [DOI-ONRR/nrrd#3470]
Please read through [the document](https://doimspp-my.sharepoint.com/:w:/g/personal/thomasc_mms_gov/EZ9skZf0BjtMmwNyo8zAav0BhDl52JzCO9PsA1IwUSL3fw?e=kGLGGs) and "test" it as if you are an intern.

**Comment by eelzi-ONRR** [comment]
@lpgoldstein I think looking through all the sites to answer the questions will take a few hours - with all the meetings this week and other issues I need to finish it's not feasible for me this sprint. I can help next sprint if you need me to

**Comment by lpgoldstein** [comment]
@alexandracmONRR Thanks for doing such a thorough check.

**Comment by lpgoldstein** [comment]
@cthomasONRR please review
bottom of the onboarding checkling: https://github.com/DOI-ONRR/nrrd/wiki/Onboarding-checklist
new page: https://github.com/DOI-ONRR/nrrd/wiki/Intern-research-tips-and-tricks

**Comment by eelzi-ONRR** [comment]
I'm still going through the questions - but here's my thoughts so far: 

What pages would you find more information about ONRR.gov and NRRD user types?
I think this question is too tricky because the NRRD wiki doesn't call they user types directly - it only refers to them as user scenarios.

How would you find information about past user research studies?
I like the question, but this is in the research repo but not part of the research wiki, and I can't find anywhere in the research or site wikis where we link to the repo files . We need to make it easier to find from the wiki if we're going to ask about it

**Comment by eelzi-ONRR** [comment]
What data is available for Native American lands?
Change to "Name 3 kinds of data available for Native American lands". I think asking the broader question is too difficult given we have long-time ONRR employees who were not clear on if/why Native American data was not included in the sales data set. We have at least 3 data sets where it's obvious Native American is included.

Where would you go to find out more about digital innovation in the federal government?
Maybe be more specific. "What are two sites or blogs where you can learn more about digital innovation in the federal government?"

All the other questions are answerable and make sense. Thanks for working on this!

**Comment by lpgoldstein** [comment]
@eelzi-ONRR I've updated based on your comments. Thanks for reviewing!

**Comment by cthomasONRR** [comment]
@lpgoldstein I made some minor typo fixes on the wiki page. Looks good. I think this can be closed now.
