### ISSUE TITLE
Incorporate user types into the product framing

### ISSUE THREAD

**Issue by eelzi-ONRR** [DOI-ONRR/nrrd#3492]
Similar to how we have the product framing for onrr.gov - we need to incorporate the user types into the scenarios section on the NRRD wiki. User types also need to be updated to include stakeholders and the changes we recently made to the product framing. The triangle image also needs to be updated.

Once this is done mark the old user types page as archived and no longer updated, and link to the new user types section on the wiki from it.

**Comment by AlexandracmONRR** [comment]
I've tagged you in this issue to review different items.

@lpgoldstein - would you please review these two sections:
https://github.com/DOI-ONRR/nrrd/wiki/Product-framing#onrr-collaborators
https://github.com/DOI-ONRR/research/blob/main/nrrd-research/00_UserTypes/00_UserTypes.md#user-type-5-onrr-collaborator

@cthomasONRR - I've brainstormed a few different names for this user type, the one I selected was "ONRR Collaborator" because these internal employees are either collaborating with others to provide others with information, validate ONRR data, or provide data to the ODDD team. 
Other words we could use (with "ONRR" before) are: sharer, partakers, contributor, involved, helper, participator, user, partner.

**Comment by lpgoldstein** [comment]
@AlexandracmONRR I love that term

**Comment by lpgoldstein** [comment]
@AlexandracmONRR Can you please delete "and direction from leadership" from the 3rd bullet point from pain points for collaborators?

**Comment by AlexandracmONRR** [comment]
@lpgoldstein - done!

**Comment by cthomasONRR** [comment]
@AlexandracmONRR I think "ONRR Collaborator" is great. Thanks for renaming!

**Comment by lpgoldstein** [comment]
@AlexandracmONRR I read through one more time and just deleted an extra "then" I think it had been there for a while. I think it's good to go and thank you for doing this!

**Comment by AlexandracmONRR** [comment]
@lpgoldstein and @cthomasONRR - thank you both for your input! Closing this issue now!
