### ISSUE TITLE
Create a FY24 analytics/metrics report out visual

### ISSUE THREAD

**Issue by lpgoldstein** [DOI-ONRR/nrrd#3587]
@cthomasONRR I'll explain tomorrow morning.

**Comment by cthomasONRR** [comment]
@lpgoldstein @AlexandracmONRR FY24 analytics for all sites are located [here](https://doimspp-my.sharepoint.com/:x:/r/personal/thomasc_mms_gov/Documents/CLT%20Analytics/FY24Analytics.xlsx?d=wf1aae332d5e54dea9a6c5058f70c8dd0&csf=1&web=1&e=TDrxyA)

This consolidated data is preliminary. I plan to pull more detailed data for all metrics after September is complete. This data is a mix of GA4 DOI Agency property data and GA4 ODDD private property data. Because we didn't have our private property set up at the start of this FY, and because the DOI Agency property data wasn't the best quality at the start of this FY, this data is meant to be ballpark only. These numbers will likely be different that what is posted on the wiki later.

**Comment by cthomasONRR** [comment]
@lpgoldstein ONRR content audit updates:

- 1,1222 externals links updated to open in the same tab.
    - Only links opening in new tab are 9 footer external links (issue set to fix soon),
    - and PDFs- 972 PDF links open in new tab.
- 1,341 external links updated to have external indicators.
- 193 link titles updated to remove ambiguity.
- 1,112 additional Q4 updates addressing standardization, addition of content, accessibility upgrades, and other miscellaneous fixes.
- Overall, 4,034 content items cataloged and audited this FY.

Will work on NRRD headliners too.

**Comment by cthomasONRR** [comment]
@lpgoldstein NRRD content audit updates

- NRRD largely in maintenance mode for Q4 
- NRRD links already open in same tab by default
- 259 links had external indicators added in Q3
- 21 links were updated in Q4 
- In total, 1,466 content items audited this FY.
- In total, 734 content updates for entire FY addressing standardization, addition/revisions of content, accessibility upgrades, and other miscellaneous fixes.

**Comment by AlexandracmONRR** [comment]
@lpgoldstein - I've finished my metrics and I attempted to take note of the accessibility metrics (but could use another sweep).

I also wonder if it makes sense for us to have a metric about M-23-22 issues. Maybe this is something that we consider for FY25? I was just thinking M-23-22 aims to improve DX, which is closely related to our user research and design goal, and looking into M-23-22 requirements has become a big part of our work, so maybe we should consider it!

**Comment by AlexandracmONRR** [comment]
Consider adding Touchpoints feedback in FY25

**Comment by cthomasONRR** [comment]
@lpgoldstein I finished filling out the FY24 Goals excel with all analytics.

**Comment by cthomasONRR** [comment]
@lpgoldstein I reviewed the PPT and it looks great! Thanks!
