### ISSUE TITLE
NRRD Analytics - strange search results

### ISSUE THREAD

**Issue by cthomasONRR** [DOI-ONRR/nrrd#3676]
For both DOI Agency Property and ODDD Property. Starting in September, and increasing in October and November, the NRRD site searching are showing code/script requests and not keyword searches. I do not think this is reflective of actual search results. No settings were modified in GA4. I'd like to double check the code to make sure everything is ok.

<img width="1242" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTc2Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5d7614f8cf00d11862d0940d88b38790ead29ec1/image.png" alt="image.png" />

**Comment by greensomes** [comment]
These search terms indicate either some one with malicious intent or security is probing the site for vulnerabilities. My guess it is security since one of the scripts entered uses oastify.com. OAST is Out-of-Band Application Security Testing and is used for penetration testing. Also, there are relatively few attempts, so no fear of bots probing for vulnerabilities.

Ideally, the search input is sanitized so SQL scripts and JavaScript is not passed to the server. We'd like to not see these searches executed and displayed in our analytics.

I will create a new issue for sanitizing the search input. @cthomasONRR, unless you disagree, I think it's ok to close this issue.

**Comment by cthomasONRR** [comment]
@greensomes Thank you for looking into this- creating a new issue for sanitizing search input sounds good!
